version: '3'

services:

  mongodb:
    image: mongo:4.0.5
    ports:
      - 27017:27017
      
  tournament-server:
    image: tournament-server:latest
    environment:
      - profile=testdata
    depends_on:
      - mongodb
    ports:
      - 8080:8080